[tool.poetry]
name = "tna-django-application"
version = "0.1.0"
description = ""
authors = ["Andrew Hosgood <andrew.hosgood@nationalarchives.gov.uk>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.14"
tna-frontend-jinja = "0.44.0"
django = "6.1"
psycopg2-binary = "2.9.12"
whitenoise = "6.12.0"
pymssql = "2.3.13"
sentry-sdk = "2.68.0"
nh3 = "0.3.6"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
requests-mock = "1.12.1"
pytest-django = "4.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'

[tool.pytest.ini_options]
testpaths = [
    "test",
]
DJANGO_SETTINGS_MODULE = "config.settings.test"

[solver]
min-release-age = 7