# Generated by Django 5.2.8 on 2025-12-04 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingAids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Finding Aid',
                'verbose_name_plural': 'Finding Aids',
            },
        ),
        migrations.CreateModel(
            name='FindingAidsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Finding Aids Location',
                'verbose_name_plural': 'Finding Aids Locations',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='management_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_management_committee', to='hospitaldetails.managementcommittee'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1948_status',
            field=models.ManyToManyField(blank=True, related_name='hospitals_post_1948_status', to='hospitaldetails.post1948status'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1948_type',
            field=models.ManyToManyField(blank=True, related_name='hospitals_post_1948_type', to='hospitaldetails.post1948type'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1974_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_post_1974_county', to='hospitaldetails.post1974county'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1982_district_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_post_1982_district_authority', to='hospitaldetails.post1982districtauthority'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1982_regional_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_post_1982_regional_authority', to='hospitaldetails.post1982regionalauthority'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='post_1996_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_post_1996_county', to='hospitaldetails.post1996county'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pre_1948_status',
            field=models.ManyToManyField(blank=True, related_name='hospitals_pre_1948_status', to='hospitaldetails.pre1948status'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pre_1948_type',
            field=models.ManyToManyField(blank=True, related_name='hospitals_pre_1948_type', to='hospitaldetails.pre1948type'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pre_1974_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_pre_1974_county', to='hospitaldetails.pre1974county'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pre_1982_district_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_pre_1982_district_authority', to='hospitaldetails.pre1982districtauthority'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pre_1982_regional_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_pre_1982_regional_authority', to='hospitaldetails.pre1982regionalauthority'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='regional_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_regional_board', to='hospitaldetails.regionalboard'),
        ),
        migrations.CreateModel(
            name='RecordsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_start', models.IntegerField(blank=True, help_text='Year the administrative records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('administrative_finish', models.IntegerField(blank=True, help_text='Year the administrative records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('general_start', models.IntegerField(blank=True, help_text='Year the general records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('general_finish', models.IntegerField(blank=True, help_text='Year the general records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('finance_start', models.IntegerField(blank=True, help_text='Year the finance records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('finance_finish', models.IntegerField(blank=True, help_text='Year the finance records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('estates_start', models.IntegerField(blank=True, help_text='Year the estates records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('estates_finish', models.IntegerField(blank=True, help_text='Year the estates records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('nursing_start', models.IntegerField(blank=True, help_text='Year the nursing records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('nursing_finish', models.IntegerField(blank=True, help_text='Year the nursing records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('staff_start', models.IntegerField(blank=True, help_text='Year the staff records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('staff_finish', models.IntegerField(blank=True, help_text='Year the staff records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('ephemera_start', models.IntegerField(blank=True, help_text='Year the ephemera records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('ephemera_finish', models.IntegerField(blank=True, help_text='Year the ephemera records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('pictorial_start', models.IntegerField(blank=True, help_text='Year the pictorial records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('pictorial_finish', models.IntegerField(blank=True, help_text='Year the pictorial records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('private_papers_start', models.IntegerField(blank=True, help_text='Year the private papers records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('private_papers_finish', models.IntegerField(blank=True, help_text='Year the private papers records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('other_start', models.IntegerField(blank=True, help_text='Year the other records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('other_finish', models.IntegerField(blank=True, help_text='Year the other records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('patients_start', models.IntegerField(blank=True, help_text='Year the patients records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('patients_finish', models.IntegerField(blank=True, help_text='Year the patients records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('admission_start', models.IntegerField(blank=True, help_text='Year the admission records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('admission_finish', models.IntegerField(blank=True, help_text='Year the admission records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('clinical_start', models.IntegerField(blank=True, help_text='Year the clinical records start (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('clinical_finish', models.IntegerField(blank=True, help_text='Year the clinical records finish (YYYY)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)])),
                ('records_notes', models.TextField(blank=True, null=True)),
                ('finding_aids_details', models.TextField(blank=True, null=True)),
                ('more_research_required', models.BooleanField(default=False)),
                ('researcher_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('finding_aids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_info', to='hospitaldetails.findingaids')),
                ('finding_aids_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_info', to='hospitaldetails.findingaidslocation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_info', to='hospitaldetails.hospital')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_info', to='hospitaldetails.repository')),
            ],
        ),
    ]
