# Generated by Django 5.2.8 on 2025-12-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0002_findingaids_findingaidslocation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordsinfo',
            options={'ordering': ['hospital__name', 'repository__name']},
        ),
    ]
