# Generated by Django 5.2.8 on 2025-12-04 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitaldetails", "0002_findingaids_findingaidslocation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordsinfo",
            options={"ordering": ["hospital__name", "repository__name"]},
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name_since",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital has had this name since (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
