# Generated by Django 5.2.9 on 2025-12-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitaldetails", "0003_alter_recordsinfo_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="name_since",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital has had this name since (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
