# Generated by Django 5.2.9 on 2025-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitaldetails", "0003_alter_recordsinfo_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordsinfo",
            name="finding_aids",
        ),
        migrations.RemoveField(
            model_name="recordsinfo",
            name="finding_aids_location",
        ),
        migrations.AddField(
            model_name="recordsinfo",
            name="finding_aids",
            field=models.ManyToManyField(
                blank=True,
                related_name="records_info",
                to="hospitaldetails.findingaids",
            ),
        ),
        migrations.AddField(
            model_name="recordsinfo",
            name="finding_aids_location",
            field=models.ManyToManyField(
                blank=True,
                related_name="records_info",
                to="hospitaldetails.findingaidslocation",
            ),
        ),
    ]
