# Generated by Django 5.2.9 on 2025-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitaldetails", "0004_remove_recordsinfo_finding_aids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="repository_code",
        ),
        migrations.AddField(
            model_name="recordsinfo",
            name="repository_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
