# Generated by Django 5.2.9 on 2026-01-15 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitaldetails", "0005_remove_repository_repository_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="address_since",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital moved to this address (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="closure_date",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital closed (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="foundation_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital was founded (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name_since",
            field=models.IntegerField(
                blank=True,
                help_text="Year the hospital has had this name since (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="administrative_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the administrative records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="administrative_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the administrative records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="admission_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the admission records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="admission_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the admission records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="clinical_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the clinical records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="clinical_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the clinical records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="ephemera_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the ephemera records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="ephemera_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the ephemera records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="estates_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the estates records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="estates_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the estates records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="finance_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the finance records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="finance_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the finance records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="general_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the general records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="general_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the general records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="nursing_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the nursing records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="nursing_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the nursing records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="other_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the other records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="other_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the other records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="patients_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the patients records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="patients_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the patients records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="pictorial_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the pictorial records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="pictorial_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the pictorial records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="private_papers_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the private papers records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="private_papers_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the private papers records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="staff_finish",
            field=models.IntegerField(
                blank=True,
                help_text="Year the staff records finish (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recordsinfo",
            name="staff_start",
            field=models.IntegerField(
                blank=True,
                help_text="Year the staff records start (YYYY)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
