# Generated by Django 6.0.3 on 2026-06-12 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospitaldetails", "0006_alter_hospital_address_since_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital",
            options={
                "ordering": ["name"],
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
            },
        ),
        migrations.AlterModelOptions(
            name="managementcommittee",
            options={
                "ordering": ["name"],
                "verbose_name": "Management Committee",
                "verbose_name_plural": "Management Committees",
            },
        ),
        migrations.AlterModelOptions(
            name="post1948status",
            options={
                "ordering": ["value"],
                "verbose_name": "Post-1948 Status",
                "verbose_name_plural": "Post-1948 Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="post1948type",
            options={
                "ordering": ["value"],
                "verbose_name": "Post-1948 Type",
                "verbose_name_plural": "Post-1948 Types",
            },
        ),
        migrations.AlterModelOptions(
            name="post1974county",
            options={
                "ordering": ["name"],
                "verbose_name": "Post-1974 County",
                "verbose_name_plural": "Post-1974 Counties",
            },
        ),
        migrations.AlterModelOptions(
            name="post1982districtauthority",
            options={
                "ordering": ["name"],
                "verbose_name": "Post-1982 District Authority",
                "verbose_name_plural": "Post-1982 District Authorities",
            },
        ),
        migrations.AlterModelOptions(
            name="post1982regionalauthority",
            options={
                "ordering": ["name"],
                "verbose_name": "Post-1982 Regional Authority",
                "verbose_name_plural": "Post-1982 Regional Authorities",
            },
        ),
        migrations.AlterModelOptions(
            name="post1996county",
            options={
                "ordering": ["name"],
                "verbose_name": "Post-1996 County",
                "verbose_name_plural": "Post-1996 Counties",
            },
        ),
        migrations.AlterModelOptions(
            name="pre1948status",
            options={
                "ordering": ["value"],
                "verbose_name": "Pre-1948 Status",
                "verbose_name_plural": "Pre-1948 Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="pre1948type",
            options={
                "ordering": ["value"],
                "verbose_name": "Pre-1948 Type",
                "verbose_name_plural": "Pre-1948 Types",
            },
        ),
        migrations.AlterModelOptions(
            name="pre1974county",
            options={
                "ordering": ["name"],
                "verbose_name": "Pre-1974 County",
                "verbose_name_plural": "Pre-1974 Counties",
            },
        ),
        migrations.AlterModelOptions(
            name="pre1982districtauthority",
            options={
                "ordering": ["name"],
                "verbose_name": "Pre-1982 District Authority",
                "verbose_name_plural": "Pre-1982 District Authorities",
            },
        ),
        migrations.AlterModelOptions(
            name="pre1982regionalauthority",
            options={
                "ordering": ["name"],
                "verbose_name": "Pre-1982 Regional Authority",
                "verbose_name_plural": "Pre-1982 Regional Authorities",
            },
        ),
        migrations.AlterModelOptions(
            name="recordsinfo",
            options={
                "ordering": ["hospital__name", "repository__name"],
                "verbose_name": "Records Information",
                "verbose_name_plural": "Records Information",
            },
        ),
        migrations.AlterModelOptions(
            name="regionalboard",
            options={
                "ordering": ["name"],
                "verbose_name": "Regional Board",
                "verbose_name_plural": "Regional Boards",
            },
        ),
        migrations.AlterModelOptions(
            name="repository",
            options={
                "ordering": ["name"],
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
            },
        ),
    ]
